image: docker/compose:latest

.before_script: &before_script
  - apk add jq
  - cd tests
  - echo "$ENV" > .env
  - echo "$CYPRESS_ENV_JSON" > cypress.env.json

before_script:
  - *before_script

services:
  - docker:dind

stages:
  - test

.app_tests:
  except:
    - merge_requests
  script:
    # Start containers
    - docker-compose up -d
    # Fix permissions of custom apps folder
    - docker exec $(docker ps -qf "name=app") sh -c 'chown www-data:root custom_apps'
    # Disable first run wizard app when nextcloud is up
    - sleep 30
    - docker exec -u www-data $(docker ps -qf "name=app") sh -c 'php -f ./occ app:disable firstrunwizard'
    # Get the IP of the web container
    - export SERVER_IP=$(docker container inspect -f '{{ .NetworkSettings.Networks.tests_default.IPAddress }}' $(docker ps -qf "name=web"))
    # Run tests in cypress container
    - docker run --network tests_default -v $CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME -w $CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME cypress/browsers:node18.12.0-chrome107 sh -c "cd tests && npm ci && export CYPRESS_NC_VERSION=$NC_VERSION && npm test -- --config baseUrl=http://$SERVER_IP"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - tests/cypress/screenshots
      - tests/cypress/videos
      - tests/nextcloud.log
    reports:
      junit:
        - tests/results/TEST-*.xml
  after_script:
    - cd tests
    # Echo log file for debug purposes
    - docker exec $(docker ps -qf "name=app") sh -c 'cat data/nextcloud.log' > nextcloud.log
    - cat nextcloud.log | jq .message
    # Shut down containers
    - docker-compose down -v

app_test_nc_25:
  extends: .app_tests
  before_script:
    - sed -i "s#nextcloud:27-fpm-alpine#nextcloud:25-fpm-alpine#g" tests/docker-compose.yml
    - export NC_VERSION=25
    - *before_script

app_test_nc_26:
  extends: .app_tests
  before_script:
    - sed -i "s#nextcloud:27-fpm-alpine#nextcloud:26-fpm-alpine#g" tests/docker-compose.yml
    - export NC_VERSION=26
    - *before_script

app_test_nc_27:
  extends: .app_tests
  before_script:
    - export NC_VERSION=27
    - *before_script

unit_tests:
  image: node:14
  except:
    - merge_requests
  before_script:
    # Navigate to main folder
    - cd $CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    # Install dependencies
    - npm ci
  script:
    # Run jest tests
    - npm run test
